name: Java CI with Gradle

on:
  push:
    paths:
    - 'viikko3/WebLogin/**'
    - '!viikko3/WebLogin/docs/**'

jobs:
  run_tests:

    runs-on: ubuntu-latest
    env: 
      working-directory: ./viikko3/WebLogin/

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ${{env.working-directory}}
      
    - name: Test with Gradle
      run: ./gradlew test
