name: viikko4 - MaksukorttiMockito

on:
  push:
    paths:
    - 'viikko4/MaksukorttiMockito/**'

defaults:
  run:
    working-directory: ./viikko4/MaksukorttiMockito/
    
jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Test with Gradle
      run: ./gradlew test
