name: Viikko 4

on:
  push:
    paths:
    - 'viikko4/**'
    
jobs:
  MockitoDemo:
  
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./viikko4/MockitoDemo/

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Test with Gradle
      run: ./gradlew test

  MaksukorttiMockito:
  
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./viikko4/MaksukorttiMockito/

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Test with Gradle
      run: ./gradlew test    
       
  Verkkokauppa:
  
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./viikko4/Verkkokauppa/

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Test with Gradle
      run: ./gradlew test   
      
       
  intJoukko:
  
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./viikko4/intJoukkoSovellus/

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Test with Gradle
      run: ./gradlew test                
